on error resume next 
set t=createobject("MERALANT.Shell")
msgbox"SYSTEM ERROR",16,"#@VIRUS#/\#MER@LANT#"
msgbox"SYSTEM ERROR",16,"#@VIRUS#/\#MER@LANT#"
msgbox"SYSTEM ERROR",16,"#@VIRUS#/\#MER@ALANT#"
msgbox"SYSTEM ERROR",16,"#@VIRUS#/\#MER@LANT#"
msgbox"SYSTEM ERROR",16,"#@VIRUS#/\#MER@LANT#"
msgbox"SYSTEM ERROR",16,"#@VIRUS#/\#MER@LANT#"
msgbox"SYSTEM ERROR",16,"#@VIRUS#/\#MER@LANT#"
msgbox"SYSTEM ERROR",16,"#@VIRUS#/\#MER@LANT#"
MsgBox"Hello!",50,"#@VIRUS#/\#MER@LANT#"
msgbox"No...",16,"#@VIRUS#/\#WORM@#"
msgbox"You deleted me? I DELETE YOUR WINDOWS",48,"#@VIRUS#/\#MER@LANT#"
msgbox"Avast antivirus detected virus, delete?",36,"ANTIVIRUS"
msgbox"I...",48,"#@VIRUS#/\#WORM@#"
msgbox"FORMATING WINDOWS",16,"SYSTEM"
msgbox"FORMATING WINDOWS",16,"SYSTEM"
msgbox"FORMATING WINDOWS",16,"SYSTEM"
msgbox"FORMATING WINDOWS",16,"SYSTEM"
msgbox"FORMATING WINDOWS",16,"SYSTEM"
msgbox"FORMATING Windows",16,"SYSTEM"
msgbox"FORMATING WINDOWS",16,"SYSTEM"
msgbox"FORMATING WINDOWS",16,"SYSTEM"
msgbox"ERROR",65,"SYSTEM"
msgbox"Shotdown from 5 sec...",65,"SYSTEM"
msgbox"Shotdown from 4 sec...",65,"SYSTEM"
msgbox"Shotdown from 3 sec...",65,"SYSTEM"
msgbox"Shotdown from 2 sec...",65,"SYSTEM"
msgbox"Shotdown from 1 sec...",65,"SYSTEM"
msgbox"Shotdown from #0000 sec...",65,"SYSTEM"

msgbox"ERROR",65,"SYSTEM"
msgbox"FORMATING disk C://",36,"#@VIRUS#/\#MER@LANT#"
msgbox"FORMATING disk C://",36,"#@VIRUS#/\#MER@LANT#"
msgbox"FORMATING disk C://",36,"#@VIRUS#/\#MER@LANT#"
msgbox"FORMATING disk C://",36,"#@VIRUS#/\#MER@LANT#"
msgbox"FORMATING disk C://",36,"#@VIRUS#/\#MER@LANT#"
msgbox"FORMATING disk C://",36,"#@VIRUS#/\#MER@LANT#"
msgbox"FORMATING disk C://",36,"#@VIRUS#/\#MER@LANT#"
msgbox"FORMATING disk C://",36,"#@VIRUS#/\#MER@LANT#"
msgbox"FORMATING disk C://",36,"#@VIRUS#/\#MER@LANT#"
msgbox"DONE",48,"SYSTEM"
msgbox"ERROR",48,"SYSTEM"
msgbox"*DEAD*",48,"SYSTEM"