msgbox"No...",16,"#@VIRUS#/\#WORM@#"
msgbox"LOSER",48,"#@VIRUS#/\#MER@LANT#"
msgbox"OMG YOU LOOOSSSEERR",48,"#@VIRUS#/\#WORM@#"
msgbox"LOSEEE",16,"SYSTEM"
msgbox"I FORMATING YOU DISK!",16,"SYSTEM"
msgbox"FORMATING DISK",16,"SYSTEM"
msgbox"FORMATING DISK",16,"SYSTEM"
msgbox"FORMATING DISK",16,"SYSTEM"
msgbox"FORMATING DISK",16,"SYSTEM"
msgbox"FORMATING DISK",16,"SYSTEM"
msgbox"FORMATING DISK",16,"SYSTEM"
msgbox"ERROR",65,"SYSTEM"
msgbox"Shotdown from 5 sec...",65,"SYSTEM"
msgbox"Shotdown from 4 sec...",65,"SYSTEM"
msgbox"Shotdown from 3 sec...",65,"SYSTEM"
msgbox"Shotdown from 2 sec...",65,"SYSTEM"
msgbox"Shotdown from 1 sec...",65,"SYSTEM"
msgbox"Shotdown from #0000 sec...",65,"SYSTEM"